apiVersion: v1
kind: ConfigMap
metadata:
  name: rhiza-config
  namespace: rhiza
data:
  RHIZA_CLUSTER_ID: "cluster-a"
  RHIZA_EXECUTION_PROFILE: "sql"
  RHIZA_BIND_ADDR: "0.0.0.0:8080"
  RHIZA_PEER_ADDR: "0.0.0.0:9090"
  RHIZA_DATA_DIR: "/data"
  RHIZA_OBJSTORE_PROVIDER: "filesystem"
  RHIZA_FILESYSTEM_DIR: "/objstore"
