[package]
name = "rhiza-graph"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "LadybugDB materialized state machine for rhiza graph"

[dependencies]
lbug = "=0.18.1"
rhiza-core = { version = "0.3.0", path = "../rhiza-core" }
tempfile.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest = "1"
