apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: rhiza-two-peer-failure
  namespace: rhiza-3peer-e2e
spec:
  action: pod-failure
  mode: all
  duration: 20s
  selector:
    pods:
      rhiza-3peer-e2e:
        - rhiza-sql-0
        - rhiza-sql-2
  containerNames:
    - rhiza-sql
