// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DecisionT struct {
	Slot uint64 `json:"slot"`
	Step uint64 `json:"step"`
	Proposal *ProposalT `json:"proposal"`
	Summaries []*SummaryT `json:"summaries"`
}

func (t *DecisionT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	proposalOffset := t.Proposal.Pack(builder)
	summariesOffset := flatbuffers.UOffsetT(0)
	if t.Summaries != nil {
		summariesLength := len(t.Summaries)
		summariesOffsets := make([]flatbuffers.UOffsetT, summariesLength)
		for j := 0; j < summariesLength; j++ {
			summariesOffsets[j] = t.Summaries[j].Pack(builder)
		}
		DecisionStartSummariesVector(builder, summariesLength)
		for j := summariesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(summariesOffsets[j])
		}
		summariesOffset = builder.EndVector(summariesLength)
	}
	DecisionStart(builder)
	DecisionAddSlot(builder, t.Slot)
	DecisionAddStep(builder, t.Step)
	DecisionAddProposal(builder, proposalOffset)
	DecisionAddSummaries(builder, summariesOffset)
	return DecisionEnd(builder)
}

func (rcv *Decision) UnPackTo(t *DecisionT) {
	t.Slot = rcv.Slot()
	t.Step = rcv.Step()
	t.Proposal = rcv.Proposal(nil).UnPack()
	summariesLength := rcv.SummariesLength()
	t.Summaries = make([]*SummaryT, summariesLength)
	for j := 0; j < summariesLength; j++ {
		x := Summary{}
		rcv.Summaries(&x, j)
		t.Summaries[j] = x.UnPack()
	}
}

func (rcv *Decision) UnPack() *DecisionT {
	if rcv == nil {
		return nil
	}
	t := &DecisionT{}
	rcv.UnPackTo(t)
	return t
}

type Decision struct {
	_tab flatbuffers.Table
}

func GetRootAsDecision(buf []byte, offset flatbuffers.UOffsetT) *Decision {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Decision{}
	x.Init(buf, n+offset)
	return x
}

func FinishDecisionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDecision(buf []byte, offset flatbuffers.UOffsetT) *Decision {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Decision{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDecisionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Decision) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Decision) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Decision) Slot() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Decision) MutateSlot(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Decision) Step() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Decision) MutateStep(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Decision) Proposal(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Decision) Summaries(obj *Summary, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Decision) SummariesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DecisionStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DecisionAddSlot(builder *flatbuffers.Builder, slot uint64) {
	builder.PrependUint64Slot(0, slot, 0)
}
func DecisionAddStep(builder *flatbuffers.Builder, step uint64) {
	builder.PrependUint64Slot(1, step, 0)
}
func DecisionAddProposal(builder *flatbuffers.Builder, proposal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(proposal), 0)
}
func DecisionAddSummaries(builder *flatbuffers.Builder, summaries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(summaries), 0)
}
func DecisionStartSummariesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DecisionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
