// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DecidedValueT struct {
	Slot uint64 `json:"slot"`
	Hash []byte `json:"hash"`
	Value []byte `json:"value"`
	Certificate []byte `json:"certificate"`
}

func (t *DecidedValueT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	hashOffset := flatbuffers.UOffsetT(0)
	if t.Hash != nil {
		hashOffset = builder.CreateByteString(t.Hash)
	}
	valueOffset := flatbuffers.UOffsetT(0)
	if t.Value != nil {
		valueOffset = builder.CreateByteString(t.Value)
	}
	certificateOffset := flatbuffers.UOffsetT(0)
	if t.Certificate != nil {
		certificateOffset = builder.CreateByteString(t.Certificate)
	}
	DecidedValueStart(builder)
	DecidedValueAddSlot(builder, t.Slot)
	DecidedValueAddHash(builder, hashOffset)
	DecidedValueAddValue(builder, valueOffset)
	DecidedValueAddCertificate(builder, certificateOffset)
	return DecidedValueEnd(builder)
}

func (rcv *DecidedValue) UnPackTo(t *DecidedValueT) {
	t.Slot = rcv.Slot()
	t.Hash = rcv.HashBytes()
	t.Value = rcv.ValueBytes()
	t.Certificate = rcv.CertificateBytes()
}

func (rcv *DecidedValue) UnPack() *DecidedValueT {
	if rcv == nil {
		return nil
	}
	t := &DecidedValueT{}
	rcv.UnPackTo(t)
	return t
}

type DecidedValue struct {
	_tab flatbuffers.Table
}

func GetRootAsDecidedValue(buf []byte, offset flatbuffers.UOffsetT) *DecidedValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DecidedValue{}
	x.Init(buf, n+offset)
	return x
}

func FinishDecidedValueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDecidedValue(buf []byte, offset flatbuffers.UOffsetT) *DecidedValue {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DecidedValue{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDecidedValueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DecidedValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DecidedValue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DecidedValue) Slot() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DecidedValue) MutateSlot(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *DecidedValue) Hash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DecidedValue) HashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DecidedValue) HashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DecidedValue) MutateHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *DecidedValue) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DecidedValue) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DecidedValue) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DecidedValue) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *DecidedValue) Certificate(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *DecidedValue) CertificateLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DecidedValue) CertificateBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DecidedValue) MutateCertificate(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func DecidedValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DecidedValueAddSlot(builder *flatbuffers.Builder, slot uint64) {
	builder.PrependUint64Slot(0, slot, 0)
}
func DecidedValueAddHash(builder *flatbuffers.Builder, hash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(hash), 0)
}
func DecidedValueStartHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DecidedValueAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(value), 0)
}
func DecidedValueStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DecidedValueAddCertificate(builder *flatbuffers.Builder, certificate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(certificate), 0)
}
func DecidedValueStartCertificateVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func DecidedValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
