// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import "strconv"

type Operation byte

const (
	OperationNone              Operation = 0
	OperationRecord            Operation = 1
	OperationReservedPropose   Operation = 2
	OperationLearned           Operation = 3
	OperationSync              Operation = 4
	OperationReadIndex         Operation = 5
	OperationStageValue        Operation = 6
	OperationFetchValue        Operation = 7
	OperationPrepareCheckpoint Operation = 8
)

var EnumNamesOperation = map[Operation]string{
	OperationNone:              "None",
	OperationRecord:            "Record",
	OperationReservedPropose:   "ReservedPropose",
	OperationLearned:           "Learned",
	OperationSync:              "Sync",
	OperationReadIndex:         "ReadIndex",
	OperationStageValue:        "StageValue",
	OperationFetchValue:        "FetchValue",
	OperationPrepareCheckpoint: "PrepareCheckpoint",
}

var EnumValuesOperation = map[string]Operation{
	"None":              OperationNone,
	"Record":            OperationRecord,
	"ReservedPropose":   OperationReservedPropose,
	"Learned":           OperationLearned,
	"Sync":              OperationSync,
	"ReadIndex":         OperationReadIndex,
	"StageValue":        OperationStageValue,
	"FetchValue":        OperationFetchValue,
	"PrepareCheckpoint": OperationPrepareCheckpoint,
}

func (v Operation) String() string {
	if s, ok := EnumNamesOperation[v]; ok {
		return s
	}
	return "Operation(" + strconv.FormatInt(int64(v), 10) + ")"
}
