// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import "strconv"

type Operation byte

const (
	OperationNone      Operation = 0
	OperationRecord    Operation = 1
	OperationPropose   Operation = 2
	OperationLearned   Operation = 3
	OperationDecisions Operation = 4
)

var EnumNamesOperation = map[Operation]string{
	OperationNone:      "None",
	OperationRecord:    "Record",
	OperationPropose:   "Propose",
	OperationLearned:   "Learned",
	OperationDecisions: "Decisions",
}

var EnumValuesOperation = map[string]Operation{
	"None":      OperationNone,
	"Record":    OperationRecord,
	"Propose":   OperationPropose,
	"Learned":   OperationLearned,
	"Decisions": OperationDecisions,
}

func (v Operation) String() string {
	if s, ok := EnumNamesOperation[v]; ok {
		return s
	}
	return "Operation(" + strconv.FormatInt(int64(v), 10) + ")"
}
