// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecordRequestT struct {
	Slot     uint64     `json:"slot"`
	Step     uint64     `json:"step"`
	Proposal *ProposalT `json:"proposal"`
}

func (t *RecordRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	proposalOffset := t.Proposal.Pack(builder)
	RecordRequestStart(builder)
	RecordRequestAddSlot(builder, t.Slot)
	RecordRequestAddStep(builder, t.Step)
	RecordRequestAddProposal(builder, proposalOffset)
	return RecordRequestEnd(builder)
}

func (rcv *RecordRequest) UnPackTo(t *RecordRequestT) {
	t.Slot = rcv.Slot()
	t.Step = rcv.Step()
	t.Proposal = rcv.Proposal(nil).UnPack()
}

func (rcv *RecordRequest) UnPack() *RecordRequestT {
	if rcv == nil {
		return nil
	}
	t := &RecordRequestT{}
	rcv.UnPackTo(t)
	return t
}

type RecordRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRecordRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecordRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecordRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecordRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RecordRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecordRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RecordRequest) Slot() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RecordRequest) MutateSlot(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *RecordRequest) Step() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RecordRequest) MutateStep(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *RecordRequest) Proposal(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RecordRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RecordRequestAddSlot(builder *flatbuffers.Builder, slot uint64) {
	builder.PrependUint64Slot(0, slot, 0)
}
func RecordRequestAddStep(builder *flatbuffers.Builder, step uint64) {
	builder.PrependUint64Slot(1, step, 0)
}
func RecordRequestAddProposal(builder *flatbuffers.Builder, proposal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(proposal), 0)
}
func RecordRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
