// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RequestT struct {
	Magic     uint32          `json:"magic"`
	Operation Operation       `json:"operation"`
	ClusterId string          `json:"cluster_id"`
	SenderId  string          `json:"sender_id"`
	ConfigId  uint64          `json:"config_id"`
	Token     string          `json:"token"`
	Record    *RecordRequestT `json:"record"`
	Value     []byte          `json:"value"`
	Decision  *DecisionT      `json:"decision"`
	From      uint64          `json:"from"`
	Limit     uint32          `json:"limit"`
	Hash      []byte          `json:"hash"`
}

func (t *RequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	clusterIdOffset := flatbuffers.UOffsetT(0)
	if t.ClusterId != "" {
		clusterIdOffset = builder.CreateString(t.ClusterId)
	}
	senderIdOffset := flatbuffers.UOffsetT(0)
	if t.SenderId != "" {
		senderIdOffset = builder.CreateString(t.SenderId)
	}
	tokenOffset := flatbuffers.UOffsetT(0)
	if t.Token != "" {
		tokenOffset = builder.CreateString(t.Token)
	}
	recordOffset := t.Record.Pack(builder)
	valueOffset := flatbuffers.UOffsetT(0)
	if t.Value != nil {
		valueOffset = builder.CreateByteString(t.Value)
	}
	decisionOffset := t.Decision.Pack(builder)
	hashOffset := flatbuffers.UOffsetT(0)
	if t.Hash != nil {
		hashOffset = builder.CreateByteString(t.Hash)
	}
	RequestStart(builder)
	RequestAddMagic(builder, t.Magic)
	RequestAddOperation(builder, t.Operation)
	RequestAddClusterId(builder, clusterIdOffset)
	RequestAddSenderId(builder, senderIdOffset)
	RequestAddConfigId(builder, t.ConfigId)
	RequestAddToken(builder, tokenOffset)
	RequestAddRecord(builder, recordOffset)
	RequestAddValue(builder, valueOffset)
	RequestAddDecision(builder, decisionOffset)
	RequestAddFrom(builder, t.From)
	RequestAddLimit(builder, t.Limit)
	RequestAddHash(builder, hashOffset)
	return RequestEnd(builder)
}

func (rcv *Request) UnPackTo(t *RequestT) {
	t.Magic = rcv.Magic()
	t.Operation = rcv.Operation()
	t.ClusterId = string(rcv.ClusterId())
	t.SenderId = string(rcv.SenderId())
	t.ConfigId = rcv.ConfigId()
	t.Token = string(rcv.Token())
	t.Record = rcv.Record(nil).UnPack()
	t.Value = rcv.ValueBytes()
	t.Decision = rcv.Decision(nil).UnPack()
	t.From = rcv.From()
	t.Limit = rcv.Limit()
	t.Hash = rcv.HashBytes()
}

func (rcv *Request) UnPack() *RequestT {
	if rcv == nil {
		return nil
	}
	t := &RequestT{}
	rcv.UnPackTo(t)
	return t
}

type Request struct {
	_tab flatbuffers.Table
}

const RequestIdentifier = "RHZA"

func GetRootAsRequest(buf []byte, offset flatbuffers.UOffsetT) *Request {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Request{}
	x.Init(buf, n+offset)
	return x
}

func FinishRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(RequestIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func RequestBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, RequestIdentifier)
}

func GetSizePrefixedRootAsRequest(buf []byte, offset flatbuffers.UOffsetT) *Request {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Request{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(RequestIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedRequestBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, RequestIdentifier)
}

func (rcv *Request) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Request) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Request) Magic() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Request) MutateMagic(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Request) Operation() Operation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Operation(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Request) MutateOperation(n Operation) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *Request) ClusterId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Request) SenderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Request) ConfigId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Request) MutateConfigId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *Request) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Request) Record(obj *RecordRequest) *RecordRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RecordRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Request) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Request) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Request) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Request) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *Request) Decision(obj *Decision) *Decision {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Decision)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Request) From() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Request) MutateFrom(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func (rcv *Request) Limit() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Request) MutateLimit(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *Request) Hash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Request) HashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Request) HashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Request) MutateHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func RequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func RequestAddMagic(builder *flatbuffers.Builder, magic uint32) {
	builder.PrependUint32Slot(0, magic, 0)
}
func RequestAddOperation(builder *flatbuffers.Builder, operation Operation) {
	builder.PrependByteSlot(1, byte(operation), 0)
}
func RequestAddClusterId(builder *flatbuffers.Builder, clusterId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(clusterId), 0)
}
func RequestAddSenderId(builder *flatbuffers.Builder, senderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(senderId), 0)
}
func RequestAddConfigId(builder *flatbuffers.Builder, configId uint64) {
	builder.PrependUint64Slot(4, configId, 0)
}
func RequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(token), 0)
}
func RequestAddRecord(builder *flatbuffers.Builder, record flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(record), 0)
}
func RequestAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(value), 0)
}
func RequestStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RequestAddDecision(builder *flatbuffers.Builder, decision flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(decision), 0)
}
func RequestAddFrom(builder *flatbuffers.Builder, from uint64) {
	builder.PrependUint64Slot(9, from, 0)
}
func RequestAddLimit(builder *flatbuffers.Builder, limit uint32) {
	builder.PrependUint32Slot(10, limit, 0)
}
func RequestAddHash(builder *flatbuffers.Builder, hash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(hash), 0)
}
func RequestStartHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
