// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResponseT struct {
	Version uint16 `json:"version"`
	Error string `json:"error"`
	Summary *SummaryT `json:"summary"`
	Decided *DecidedValueT `json:"decided"`
	ClusterId string `json:"cluster_id"`
	ProposerId string `json:"proposer_id"`
	ConfigId uint64 `json:"config_id"`
	Tip uint64 `json:"tip"`
	Decisions []*DecidedValueT `json:"decisions"`
	ErrorCode uint16 `json:"error_code"`
}

func (t *ResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	errorOffset := flatbuffers.UOffsetT(0)
	if t.Error != "" {
		errorOffset = builder.CreateString(t.Error)
	}
	summaryOffset := t.Summary.Pack(builder)
	decidedOffset := t.Decided.Pack(builder)
	clusterIdOffset := flatbuffers.UOffsetT(0)
	if t.ClusterId != "" {
		clusterIdOffset = builder.CreateString(t.ClusterId)
	}
	proposerIdOffset := flatbuffers.UOffsetT(0)
	if t.ProposerId != "" {
		proposerIdOffset = builder.CreateString(t.ProposerId)
	}
	decisionsOffset := flatbuffers.UOffsetT(0)
	if t.Decisions != nil {
		decisionsLength := len(t.Decisions)
		decisionsOffsets := make([]flatbuffers.UOffsetT, decisionsLength)
		for j := 0; j < decisionsLength; j++ {
			decisionsOffsets[j] = t.Decisions[j].Pack(builder)
		}
		ResponseStartDecisionsVector(builder, decisionsLength)
		for j := decisionsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(decisionsOffsets[j])
		}
		decisionsOffset = builder.EndVector(decisionsLength)
	}
	ResponseStart(builder)
	ResponseAddVersion(builder, t.Version)
	ResponseAddError(builder, errorOffset)
	ResponseAddSummary(builder, summaryOffset)
	ResponseAddDecided(builder, decidedOffset)
	ResponseAddClusterId(builder, clusterIdOffset)
	ResponseAddProposerId(builder, proposerIdOffset)
	ResponseAddConfigId(builder, t.ConfigId)
	ResponseAddTip(builder, t.Tip)
	ResponseAddDecisions(builder, decisionsOffset)
	ResponseAddErrorCode(builder, t.ErrorCode)
	return ResponseEnd(builder)
}

func (rcv *Response) UnPackTo(t *ResponseT) {
	t.Version = rcv.Version()
	t.Error = string(rcv.Error())
	t.Summary = rcv.Summary(nil).UnPack()
	t.Decided = rcv.Decided(nil).UnPack()
	t.ClusterId = string(rcv.ClusterId())
	t.ProposerId = string(rcv.ProposerId())
	t.ConfigId = rcv.ConfigId()
	t.Tip = rcv.Tip()
	decisionsLength := rcv.DecisionsLength()
	t.Decisions = make([]*DecidedValueT, decisionsLength)
	for j := 0; j < decisionsLength; j++ {
		x := DecidedValue{}
		rcv.Decisions(&x, j)
		t.Decisions[j] = x.UnPack()
	}
	t.ErrorCode = rcv.ErrorCode()
}

func (rcv *Response) UnPack() *ResponseT {
	if rcv == nil {
		return nil
	}
	t := &ResponseT{}
	rcv.UnPackTo(t)
	return t
}

type Response struct {
	_tab flatbuffers.Table
}

func GetRootAsResponse(buf []byte, offset flatbuffers.UOffsetT) *Response {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Response{}
	x.Init(buf, n+offset)
	return x
}

func FinishResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResponse(buf []byte, offset flatbuffers.UOffsetT) *Response {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Response{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Response) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Response) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Response) Version() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *Response) MutateVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *Response) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Response) Summary(obj *Summary) *Summary {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Summary)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Response) Decided(obj *DecidedValue) *DecidedValue {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DecidedValue)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Response) ClusterId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Response) ProposerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Response) ConfigId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Response) MutateConfigId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *Response) Tip() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Response) MutateTip(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *Response) Decisions(obj *DecidedValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Response) DecisionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Response) ErrorCode() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Response) MutateErrorCode(n uint16) bool {
	return rcv._tab.MutateUint16Slot(22, n)
}

func ResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func ResponseAddVersion(builder *flatbuffers.Builder, version uint16) {
	builder.PrependUint16Slot(0, version, 1)
}
func ResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func ResponseAddSummary(builder *flatbuffers.Builder, summary flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(summary), 0)
}
func ResponseAddDecided(builder *flatbuffers.Builder, decided flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(decided), 0)
}
func ResponseAddClusterId(builder *flatbuffers.Builder, clusterId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(clusterId), 0)
}
func ResponseAddProposerId(builder *flatbuffers.Builder, proposerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(proposerId), 0)
}
func ResponseAddConfigId(builder *flatbuffers.Builder, configId uint64) {
	builder.PrependUint64Slot(6, configId, 0)
}
func ResponseAddTip(builder *flatbuffers.Builder, tip uint64) {
	builder.PrependUint64Slot(7, tip, 0)
}
func ResponseAddDecisions(builder *flatbuffers.Builder, decisions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(decisions), 0)
}
func ResponseStartDecisionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ResponseAddErrorCode(builder *flatbuffers.Builder, errorCode uint16) {
	builder.PrependUint16Slot(9, errorCode, 0)
}
func ResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
