// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package peerfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SummaryT struct {
	RecorderId string `json:"recorder_id"`
	Step uint64 `json:"step"`
	FirstCurrent *ProposalT `json:"first_current"`
	AggregatePrior *ProposalT `json:"aggregate_prior"`
}

func (t *SummaryT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	recorderIdOffset := flatbuffers.UOffsetT(0)
	if t.RecorderId != "" {
		recorderIdOffset = builder.CreateString(t.RecorderId)
	}
	firstCurrentOffset := t.FirstCurrent.Pack(builder)
	aggregatePriorOffset := t.AggregatePrior.Pack(builder)
	SummaryStart(builder)
	SummaryAddRecorderId(builder, recorderIdOffset)
	SummaryAddStep(builder, t.Step)
	SummaryAddFirstCurrent(builder, firstCurrentOffset)
	SummaryAddAggregatePrior(builder, aggregatePriorOffset)
	return SummaryEnd(builder)
}

func (rcv *Summary) UnPackTo(t *SummaryT) {
	t.RecorderId = string(rcv.RecorderId())
	t.Step = rcv.Step()
	t.FirstCurrent = rcv.FirstCurrent(nil).UnPack()
	t.AggregatePrior = rcv.AggregatePrior(nil).UnPack()
}

func (rcv *Summary) UnPack() *SummaryT {
	if rcv == nil {
		return nil
	}
	t := &SummaryT{}
	rcv.UnPackTo(t)
	return t
}

type Summary struct {
	_tab flatbuffers.Table
}

func GetRootAsSummary(buf []byte, offset flatbuffers.UOffsetT) *Summary {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Summary{}
	x.Init(buf, n+offset)
	return x
}

func FinishSummaryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSummary(buf []byte, offset flatbuffers.UOffsetT) *Summary {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Summary{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSummaryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Summary) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Summary) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Summary) RecorderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Summary) Step() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Summary) MutateStep(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Summary) FirstCurrent(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Summary) AggregatePrior(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SummaryStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SummaryAddRecorderId(builder *flatbuffers.Builder, recorderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(recorderId), 0)
}
func SummaryAddStep(builder *flatbuffers.Builder, step uint64) {
	builder.PrependUint64Slot(1, step, 0)
}
func SummaryAddFirstCurrent(builder *flatbuffers.Builder, firstCurrent flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(firstCurrent), 0)
}
func SummaryAddAggregatePrior(builder *flatbuffers.Builder, aggregatePrior flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(aggregatePrior), 0)
}
func SummaryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
