package materializer

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/mrchypark/rhiza/internal/sqlpolicy"
	"github.com/mrchypark/rhiza/internal/types"
	"github.com/mrchypark/rhiza/pkg/quepaxa"
)

// Frozen fixtures generated by actual Materializer at
// 865e5a5541e72b397b3e6cb58e9cde0bff6dc690. Slot1 creates t(id INTEGER PRIMARY KEY).
// Slot2 inserts42 then CREATE TABLE aux(x INTEGER) ExpectedRowsAffected=0:
// the old engine rejects the whole command; the unfenced repaired engine commits.
func TestLegacyPolicyCannotOpenOrReplay(t *testing.T) {
	ctx := context.Background()
	legacy, err := os.ReadFile("testdata/sql-policy-legacy/slot2.bin")
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"slot1.db", "slot2.db"} {
		t.Run(name, func(t *testing.T) {
			original, err := os.ReadFile(filepath.Join("testdata/sql-policy-legacy", name))
			if err != nil {
				t.Fatal(err)
			}
			target := filepath.Join(t.TempDir(), name)
			if err = os.WriteFile(target, original, 0600); err != nil {
				t.Fatal(err)
			}
			if m, err := Open(target, 1); !errors.Is(err, sqlpolicy.ErrIncompatible) {
				if m != nil {
					m.Close()
				}
				t.Fatalf("open: %v", err)
			}
			after, err := os.ReadFile(target)
			if err != nil || !bytes.Equal(original, after) {
				t.Fatal("legacy database modified", err)
			}
		})
	}
	m, err := Open(filepath.Join(t.TempDir(), "new.db"), 1)
	if err != nil {
		t.Fatal(err)
	}
	defer m.Close()
	good := policySQL(t, "CREATE TABLE fresh(id INTEGER)")
	if err = m.Apply(ctx, 1, good); err != nil {
		t.Fatal(err)
	}
	for _, slot := range []uint64{0, 1, 2} {
		if err = m.Apply(ctx, slot, legacy); !errors.Is(err, sqlpolicy.ErrIncompatible) {
			t.Fatalf("slot%d: %v", slot, err)
		}
	}
	if err = m.ValidateTip(1, legacy); !errors.Is(err, sqlpolicy.ErrIncompatible) {
		t.Fatal(err)
	}
	page := []quepaxa.DecidedValue{{Slot: 2, Value: policySQL(t, "INSERT INTO fresh VALUES(1)")}, {Slot: 3, Value: legacy}}
	if err = m.ApplyBatch(ctx, page); !errors.Is(err, sqlpolicy.ErrIncompatible) {
		t.Fatal(err)
	}
	if m.Tip() != 1 {
		t.Fatal("advanced incompatible page")
	}
	rows, err := m.Query(ctx, "SELECT COUNT(*) FROM fresh")
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
	var count int
	rows.Next()
	if err = rows.Scan(&count); err != nil || count != 0 {
		t.Fatal(count, err)
	}
	rows.Close()
	if _, found, err := m.MutationReceipt(ctx, types.MutationSQL, "ddl-guard"); err != nil || found {
		t.Fatal("manufactured receipt", err)
	}
}

func TestLegacySnapshotRefusalPreservesLiveState(t *testing.T) {
	ctx := context.Background()
	m, err := Open(filepath.Join(t.TempDir(), "current.db"), 1)
	if err != nil {
		t.Fatal(err)
	}
	defer m.Close()
	if err = m.Apply(ctx, 1, policySQL(t, "CREATE TABLE current_state(id INTEGER)")); err != nil {
		t.Fatal(err)
	}
	if err = m.RestoreCheckpoint(ctx, []CheckpointFile{{Role: CheckpointSQLite, Path: "testdata/sql-policy-legacy/slot2.db"}, {Role: CheckpointGraphData, Path: "not-installed"}}); !errors.Is(err, sqlpolicy.ErrIncompatible) {
		t.Fatalf("restore: %v", err)
	}
	if m.Tip() != 1 {
		t.Fatal("restore changed tip")
	}
	if err = m.Apply(ctx, 2, policySQL(t, "INSERT INTO current_state VALUES(7)")); err != nil {
		t.Fatal(err)
	}
}

func TestMaterializationPolicyMarkerIsRequired(t *testing.T) {
	for _, marker := range []string{"", "2", "not-a-version"} {
		t.Run(marker, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "state.db")
			m, err := Open(path, 1)
			if err != nil {
				t.Fatal(err)
			}
			if marker == "" {
				_, err = m.db.Exec(`DELETE FROM _rhiza_meta WHERE key='sql_execution_policy'`)
			} else {
				_, err = m.db.Exec(`UPDATE _rhiza_meta SET value=? WHERE key='sql_execution_policy'`, marker)
			}
			if err != nil {
				t.Fatal(err)
			}
			m.Close()
			if other, err := Open(path, 1); !errors.Is(err, sqlpolicy.ErrIncompatible) {
				if other != nil {
					other.Close()
				}
				t.Fatal(err)
			}
		})
	}
}
