// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package walfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecorderStateT struct {
	Slot             uint64     `json:"slot"`
	Step             uint64     `json:"step"`
	FirstCurrent     *ProposalT `json:"first_current"`
	AggregateCurrent *ProposalT `json:"aggregate_current"`
	AggregatePrior   *ProposalT `json:"aggregate_prior"`
}

func (t *RecorderStateT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	firstCurrentOffset := t.FirstCurrent.Pack(builder)
	aggregateCurrentOffset := t.AggregateCurrent.Pack(builder)
	aggregatePriorOffset := t.AggregatePrior.Pack(builder)
	RecorderStateStart(builder)
	RecorderStateAddSlot(builder, t.Slot)
	RecorderStateAddStep(builder, t.Step)
	RecorderStateAddFirstCurrent(builder, firstCurrentOffset)
	RecorderStateAddAggregateCurrent(builder, aggregateCurrentOffset)
	RecorderStateAddAggregatePrior(builder, aggregatePriorOffset)
	return RecorderStateEnd(builder)
}

func (rcv *RecorderState) UnPackTo(t *RecorderStateT) {
	t.Slot = rcv.Slot()
	t.Step = rcv.Step()
	t.FirstCurrent = rcv.FirstCurrent(nil).UnPack()
	t.AggregateCurrent = rcv.AggregateCurrent(nil).UnPack()
	t.AggregatePrior = rcv.AggregatePrior(nil).UnPack()
}

func (rcv *RecorderState) UnPack() *RecorderStateT {
	if rcv == nil {
		return nil
	}
	t := &RecorderStateT{}
	rcv.UnPackTo(t)
	return t
}

type RecorderState struct {
	_tab flatbuffers.Table
}

const RecorderStateIdentifier = "QISR"

func GetRootAsRecorderState(buf []byte, offset flatbuffers.UOffsetT) *RecorderState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecorderState{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecorderStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(RecorderStateIdentifier)
	builder.FinishWithFileIdentifier(offset, identifierBytes)
}

func RecorderStateBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.BufferHasIdentifier(buf, RecorderStateIdentifier)
}

func GetSizePrefixedRootAsRecorderState(buf []byte, offset flatbuffers.UOffsetT) *RecorderState {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecorderState{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecorderStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	identifierBytes := []byte(RecorderStateIdentifier)
	builder.FinishSizePrefixedWithFileIdentifier(offset, identifierBytes)
}

func SizePrefixedRecorderStateBufferHasIdentifier(buf []byte) bool {
	return flatbuffers.SizePrefixedBufferHasIdentifier(buf, RecorderStateIdentifier)
}

func (rcv *RecorderState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecorderState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RecorderState) Slot() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RecorderState) MutateSlot(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *RecorderState) Step() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RecorderState) MutateStep(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *RecorderState) FirstCurrent(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RecorderState) AggregateCurrent(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RecorderState) AggregatePrior(obj *Proposal) *Proposal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Proposal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RecorderStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func RecorderStateAddSlot(builder *flatbuffers.Builder, slot uint64) {
	builder.PrependUint64Slot(0, slot, 0)
}
func RecorderStateAddStep(builder *flatbuffers.Builder, step uint64) {
	builder.PrependUint64Slot(1, step, 0)
}
func RecorderStateAddFirstCurrent(builder *flatbuffers.Builder, firstCurrent flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(firstCurrent), 0)
}
func RecorderStateAddAggregateCurrent(builder *flatbuffers.Builder, aggregateCurrent flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(aggregateCurrent), 0)
}
func RecorderStateAddAggregatePrior(builder *flatbuffers.Builder, aggregatePrior flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(aggregatePrior), 0)
}
func RecorderStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
